version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: teamnetflix
      MONGO_INITDB_ROOT_PASSWORD: nuclio
      MONGO_DATABASE_NAME: app
    ports:
      - "27022:27017"
